language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
sudo: true
before_install:
- chmod a+x ./Scripts/install.sh
install:
- "./Scripts/install.sh"
before_script:
- chmod a+x ./Scripts/build.sh
script:
- "./Scripts/build.sh"
deploy:
  provider: releases
  api_key:
    secure: eR9js9u01RxB8VJUekeWu9sKLc8fR7J7ph6/Z6XcU2Jq5EZjS6qQ7HSG0f0csdwjdUdZJV0JxqpaNQpnbpQQkL6ZvW3/i381c0qgRmewGLuvIqAvdx1OEs5JeXepjG5VRNQvqlGZgQ382HrhqSihi391sr2eCzsdSbNhV36G0FfyNg5T+nP/mzL0K2LejrTeKenc/BKrNiaBQXjxpqx+Kzh7Sehe3NjkvmplVd9XnQbsG49E93BOvoqlChH/rGWkYXTIe4uV64buyPonqBSwSryoc0GAVfRBvqqjhbGp6kMRqevE/mYAcymPs7sWZfN77XE7cokHAQ+ZxDqPmgnZKihSs/khcZIObDkeA4VQaetG+UVZ7ozw9fVCBUOBsHQMlm71FLQysmH3yLAuvUikdKg/p83q+ZtmSfugWIuaOGwcaWlOU9U3r9P8TlalbgOZtnFJmEv0x62Hy6wQ05qwbhaWHNax6XtDZm2GqcWYLB/ZgJnPfENucbzliKrzy4ZNsikh31mtB5AHPSIj0QjXotBVgO26JPbvXSkK8/NPTzR0RHHTyBDC5+lpPnMEWgj8F/tLwW3O++aMBsUOcNkM6PqjqxUMOlBZESmYO/j5I8nR1M17Jv7tuf0XRkyo6er1ol3Vqgbst8OtVgnda+fREq7mQ9wi4lhCCNfPUhguju4=
  file: Build/IsoUnity.unitypackage
  skip_cleanup: true
  on:
    tags: true
